baseurl = "https://www.igluonline.com"
languageCode = "pt-br"
paginate = 10
theme = "iglu"
title = "Iglu: Design, Freelancers, Programação e Marketing Digital"
enableRobotsTXT = true
[params]
date_format = "0002-01-20T00:00:00+00:00"
description = "Iglu é o melhor lugar para tutoriais sobre Design, Photoshop, Programação, Markegin Digital e Freelance"
insta_caption = "{{caption}}"
insta_comments = "{{comments}}"
insta_img = "{{image}}"
insta_likes = "{{likes}}"
insta_link = "{{link}}"
name = "Iglu: Design, Freelancers, Programação e Marketing Digital"
[params.featured]
hide = false
[params.recentposts]
hide = false
[permalinks]
pages = "/:filename"
posts = "/:filename"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
