baseurl = "http://igluonline.netlify.com"
languageCode = "pt-br"
title = "Iglu"
theme = "iglu"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Iglu"
	description = "Iglu é o melhor lugar para tutoriais sobre Design, Photoshop, Programação, Markegin Digital e Freelance"
	insta_link = "{{link}}"
	insta_img = "{{image}}"
	insta_caption = "{{caption}}"
	insta_likes = "{{likes}}"
	insta_comments = "{{comments}}"

	# Format dates with Go's time formatting
	date_format = "02-01-2006"


	[params.featured]
		hide  = false

	[params.recentposts]
		hide  = false

[permalinks]
    posts = "/:filename"
    pages = "/:filename"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "author"
