---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: themes/iglu/static/images/uploads
public_path: "/images/uploads"
front_matter_path: images/uploads
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.28'
