---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: themes/iglu/static/images/uploads
public_path: images/uploads
front_matter_path: images/uploads
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.28'
